services:
  redis:
    image: redis:latest
    container_name: redis_tscd
    ports:
      - "6379:6379"
    command: >
      redis-server
      --appendonly yes
      --requirepass ${REDIS_PASSWORD}
      --user ${REDIS_USER} on +@all ~* >${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    restart: "no"

  neo4j_tscd:
    image: graph-builder-neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/passwordtest1"
      NEO4J_PLUGINS: "graph-data-science"
      SERVER_MEMORY_PAGECACHE_SIZE: "512M"
      SERVER_MEMORY_HEAP_INITIAL_SIZE: "512M"
      SERVER_MEMORY_HEAP_MAX_SIZE: "1G"
    volumes:
      - neo4j_data:/var/lib/neo4j/data
    restart: "unless-stopped"

volumes:
  redis_data:
  neo4j_data:
